apiVersion: v1
kind: ServiceAccount
metadata:
  name: sidecar-job-controller
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sidecar-job-controller
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sidecar-job-controller
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: sidecar-job-controller
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sidecar-job-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: sidecar-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sidecar-controller
  template:
    metadata:
      labels:
        name: sidecar-controller
    spec:
      serviceAccountName: sidecar-job-controller
      containers:
        - image: eu.gcr.io/silta-images/silta-k8s-controller-sidecars:latest
          imagePullPolicy: Always
          name: sidecar-controller
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
